physics:
  vertical_velocity: 2.0;
  max_horizontal_velocity: 2.5;
  min_horizontal_velocity: 0.1;
  block_hit_horizontal_velocity: 2.5;
  target_box_width: 3
  target_box_height: 1

signs:
  title: '[Boost]'
  join: 'Click to join'
  leave: 'Click to leave'
  status: 'Click for status'

games:
  #Sample game configuration
  Arena1:
    name: '&aArena1'
    ground: 64
    target_dist: 150
    countdown: 30
    min_players: 2
    max_players: 0
    auto_queue: true
    countdown_announce_time: 10
    game_start:
      world: world
      x: 100
      y: 64
      z: 0
      spread: 4
    game_loss:
      world: world
      x: 0
      y: 64
      z: 0
      yaw: 0
    game_lobby:
      world: world
      x: 0
      y: 64
      z: 0
      yaw: 0

